(function () {
  if (!document.getElementById('botonSoporteTecnico')) {
    document.body.insertAdjacentHTML('beforeend', `<button class="boton-soporte-tecnico" id="botonSoporteTecnico" type="button" aria-expanded="false" aria-controls="panelSoporteTecnico" aria-label="Abrir soporte técnico" title="Soporte técnico"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12a8 8 0 0 1 16 0"/><path d="M4 12v4a2 2 0 0 0 2 2h2v-6H6a2 2 0 0 0-2 2Zm16 0v4a2 2 0 0 1-2 2h-2v-6h2a2 2 0 0 1 2 2Z"/><path d="M16 18c0 1.1-.9 2-2 2h-2"/></svg></button><section class="panel-soporte-tecnico" id="panelSoporteTecnico" aria-label="Soporte técnico" hidden><header><div><span class="soporte-icono"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12a8 8 0 0 1 16 0"/><path d="M4 12v4a2 2 0 0 0 2 2h2v-6H6a2 2 0 0 0-2 2Zm16 0v4a2 2 0 0 1-2 2h-2a2 2 0 0 1 2 2Z"/></svg></span><div><strong>Soporte técnico</strong><small>Equipo SATCONTROL</small></div></div><button id="cerrarSoporteTecnico" type="button" aria-label="Cerrar soporte">×</button></header><div class="soporte-cuerpo"><p>¿Necesitas ayuda con el módulo, datos o visualización del mapa?</p><a href="mailto:soporte@satcontrol.pe?subject=Solicitud%20de%20soporte%20SATCONTROL">Enviar solicitud</a><small>Describe el módulo, la acción realizada y, si es posible, adjunta una captura.</small></div></section>`);
    const botonSoporte = document.getElementById('botonSoporteTecnico');
    const panelSoporte = document.getElementById('panelSoporteTecnico');
    const alternarSoporte = abrir => { panelSoporte.hidden = !abrir; botonSoporte.setAttribute('aria-expanded', String(abrir)); };
    botonSoporte.addEventListener('click', () => alternarSoporte(panelSoporte.hidden));
    document.getElementById('cerrarSoporteTecnico').addEventListener('click', () => alternarSoporte(false));
    document.addEventListener('keydown', evento => { if (evento.key === 'Escape' && !panelSoporte.hidden) alternarSoporte(false); });
    panelSoporte.querySelector('.soporte-cuerpo').innerHTML=`<button class="opcion-soporte" type="button" data-soporte-modal="reporte"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16v10H4z"/><path d="M8 7V5m8 2V5M8 11h.01M12 11h.01M16 11h.01M8 15h.01M12 15h.01M16 15h.01"/></svg><span>Reportar incidencia<small>Registre una solicitud para el equipo técnico.</small></span></button><button class="opcion-soporte" type="button" data-soporte-modal="lista"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6h12M8 12h12M8 18h12"/><path d="m3 6 1.2 1.2L6 4.8M3 12l1.2 1.2L6 10.8M3 18l1.2 1.2L6 16.8"/></svg><span>Incidencias reportadas<small>Consulte el estado de sus solicitudes.</small></span></button>`;
    document.body.insertAdjacentHTML('beforeend',`<section class="modal-incidencias" id="modalReportarIncidencia" hidden><div class="modal-incidencias-fondo" data-cerrar-incidencia></div><div class="modal-incidencias-contenido"><header><div><small>SOPORTE TÉCNICO</small><h2>Reportar incidencia</h2><p>Registre el detalle para que el equipo técnico pueda atenderlo.</p></div><button type="button" data-cerrar-incidencia aria-label="Cerrar">×</button></header><form id="formReportarIncidencia"><div class="campos-incidencia"><label>Módulo<select required><option value="">Seleccione</option><option>Masificación</option><option>Liquidaciones</option><option>Documentos notarizados</option><option>Acceso a la plataforma</option></select></label><label>Prioridad<select required><option>Media</option><option>Alta</option><option>Baja</option></select></label><label class="ancho">Asunto<input required placeholder="Ej. No puedo cargar el expediente del hito"></label><label class="ancho">Descripción<textarea required rows="4" placeholder="Describa qué ocurrió, la acción realizada y el resultado esperado."></textarea></label><label class="ancho">Adjuntar evidencia<input type="file" accept="image/*,.pdf"></label></div><footer><span id="mensajeIncidencia"></span><button type="submit">Enviar incidencia</button></footer></form></div></section><section class="modal-incidencias" id="modalIncidenciasReportadas" hidden><div class="modal-incidencias-fondo" data-cerrar-incidencia></div><div class="modal-incidencias-contenido"><header><div><small>SOPORTE TÉCNICO</small><h2>Incidencias reportadas</h2><p>Seguimiento de solicitudes registradas en la maqueta.</p></div><button type="button" data-cerrar-incidencia aria-label="Cerrar">×</button></header><div class="lista-incidencias" id="listaIncidencias"><article><b>INC-2026-001</b><div><strong>Validación de expediente PSR</strong><small>Masificación · 02/09/2026</small></div><em>En atención</em></article><article><b>INC-2026-002</b><div><strong>Consulta de documentos notarizados</strong><small>Repositorio · 01/09/2026</small></div><em class="resuelta">Resuelta</em></article></div></div></section>`);
    const abrirModalIncidencia=tipo=>{alternarSoporte(false);document.getElementById(tipo==='reporte'?'modalReportarIncidencia':'modalIncidenciasReportadas').hidden=false;};
    panelSoporte.querySelectorAll('[data-soporte-modal]').forEach(opcion=>opcion.addEventListener('click',()=>abrirModalIncidencia(opcion.dataset.soporteModal)));
    document.querySelectorAll('[data-cerrar-incidencia]').forEach(boton=>boton.addEventListener('click',()=>document.querySelectorAll('.modal-incidencias').forEach(modal=>modal.hidden=true)));
    document.getElementById('formReportarIncidencia').addEventListener('submit',evento=>{evento.preventDefault();document.getElementById('mensajeIncidencia').textContent='Incidencia registrada correctamente con el código INC-2026-003.';});
    document.body.insertAdjacentHTML('beforeend', `<button class="boton-documentos-notariados" id="botonDocumentosNotariados" type="button" aria-expanded="false" aria-controls="panelDocumentosNotariados" aria-label="Abrir documentos notarizados" title="Documentos notarizados"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h7l4 4v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z"/><path d="M14 3v5h5"/><rect x="9" y="12" width="6" height="5" rx="1"/><path d="M10.5 12v-1.2a1.5 1.5 0 0 1 3 0V12"/></svg></button><section class="panel-documentos-notariados" id="panelDocumentosNotariados" aria-label="Documentos notarizados" hidden><header><div><span class="documento-notariado-icono"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h7l4 4v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z"/><path d="M14 3v5h5"/><rect x="9" y="12" width="6" height="5" rx="1"/><path d="M10.5 12v-1.2a1.5 1.5 0 0 1 3 0V12"/></svg></span><div><strong>Documentos notarizados</strong><small>Repositorio documentario</small></div></div><button id="cerrarDocumentosNotariados" type="button" aria-label="Cerrar documentos">×</button></header><div class="documentos-notariados-cuerpo"><p>Consulte y registre documentos con constancia notarial vinculados a los proyectos.</p><button type="button" id="abrirRepositorioNotarial">Abrir repositorio</button><ul><li><b>0</b> documentos pendientes de revisión</li><li>La carga documental se representa en esta maqueta.</li></ul></div></section>`);
    const botonNotariado=document.getElementById('botonDocumentosNotariados'),panelNotariado=document.getElementById('panelDocumentosNotariados');
    const alternarNotariado=abrir=>{panelNotariado.hidden=!abrir;botonNotariado.setAttribute('aria-expanded',String(abrir));if(abrir)alternarSoporte(false);};
    botonNotariado.addEventListener('click',()=>alternarNotariado(panelNotariado.hidden));
    document.getElementById('cerrarDocumentosNotariados').addEventListener('click',()=>alternarNotariado(false));
    document.getElementById('abrirRepositorioNotarial').addEventListener('click',()=>{panelNotariado.querySelector('.documentos-notariados-cuerpo p').textContent='Repositorio de documentos notarizados listo para consulta en la maqueta.';});
    document.addEventListener('keydown',evento=>{if(evento.key==='Escape'&&!panelNotariado.hidden)alternarNotariado(false);});
  }
  if (document.getElementById('botonAsistenteIA')) return;
  const rutaModulo = location.pathname.toLocaleLowerCase('es');
  const modulo = rutaModulo.includes('/admin/') ? 'Administración SATCONTROL' : rutaModulo.includes('mcter') ? 'MCTER' : rutaModulo.includes('vale-fise') ? 'Vale FISE' : rutaModulo.includes('masificacion') ? 'Masificación' : 'General';
  const respuestas = {
    'Consultar manual': 'Puedo ayudarte a ubicar procedimientos, definiciones y pasos operativos dentro de la maqueta.',
    'Buscar beneficiario': modulo === 'MCTER' ? 'Utiliza el buscador superior para consultar por código MCTER y luego activa la capa de beneficiarios.' : 'Utiliza el buscador de SATCONTROL para consultar por DNI, ID FISE o código de suministro.',
    'Generar reporte': 'El reporte demostrativo puede prepararse con los filtros y el período seleccionados actualmente.',
    'Validar ubicación': 'Selecciona un registro en el mapa para revisar departamento, provincia, distrito y coordenadas.',
    'Predicción de avance': 'La predicción es demostrativa. Se calcularía con el histórico mensual y la cobertura territorial.',
    'Monitoreo KPI': 'Puedes revisar estados, cobertura y distribución desde el resumen y la sección de gráficas.',
    'Consultar mapa': 'En Mapas puedes cambiar la base; en Capas puedes controlar los registros visibles y en Temáticos revisar densidad.'
  };
  document.body.insertAdjacentHTML('beforeend', `<button class="boton-asistente-ia" id="botonAsistenteIA" type="button" aria-expanded="false" aria-label="Abrir asistente IA"><svg viewBox="0 0 24 24"><rect x="5" y="7" width="14" height="11" rx="3"/><path d="M12 4v3M8 12h.01M16 12h.01M9 16h6"/></svg></button><section class="panel-asistente-ia" id="panelAsistenteIA" aria-label="Chat del asistente IA" hidden><header class="cabecera-asistente-ia"><div class="identidad-asistente-ia"><span class="avatar-asistente-ia"><svg viewBox="0 0 24 24"><rect x="5" y="7" width="14" height="11" rx="3"/><path d="M12 4v3M8 12h.01M16 12h.01M9 16h6"/></svg></span><div><strong>Asistente Paulet IA</strong><small>En línea · ${modulo}</small></div></div><button class="cerrar-asistente-ia" id="cerrarAsistenteIA" type="button" aria-label="Cerrar asistente">×</button></header><div class="conversacion-asistente-ia" id="conversacionAsistenteIA"><div class="mensaje-ia">Hola, ¿cómo puedo ayudarte hoy?</div><div class="acciones-rapidas-ia">${Object.keys(respuestas).map(texto => `<button type="button">${texto}</button>`).join('')}</div></div><form class="pie-asistente-ia" id="formularioAsistenteIA"><input id="mensajeAsistenteIA" type="text" placeholder="Escribe tu mensaje…" autocomplete="off"><button type="submit" aria-label="Enviar mensaje"><svg viewBox="0 0 24 24"><path d="m4 4 17 8-17 8 3-8-3-8Z"/><path d="M7 12h14"/></svg></button></form></section>`);
  const accionesCabecera=document.querySelector('.cabecera-satcontrol-acciones'); const indicadorEspacio=document.querySelector('.indicador-espacio-satcontrol');
  ['botonSoporteTecnico','botonDocumentosNotariados','botonAsistenteIA'].forEach(id=>{const botonCabecera=document.getElementById(id);if(botonCabecera&&accionesCabecera)accionesCabecera.insertBefore(botonCabecera,indicadorEspacio);});
  const boton=document.getElementById('botonAsistenteIA'); const panel=document.getElementById('panelAsistenteIA'); const conversacion=document.getElementById('conversacionAsistenteIA'); const formulario=document.getElementById('formularioAsistenteIA'); const entrada=document.getElementById('mensajeAsistenteIA');
  function alternar(abrir){panel.hidden=!abrir;boton.setAttribute('aria-expanded',String(abrir));if(abrir)setTimeout(()=>entrada.focus(),50);}
  function agregar(texto,clase=''){const mensaje=document.createElement('div');mensaje.className=`mensaje-ia ${clase}`.trim();mensaje.textContent=texto;conversacion.append(mensaje);conversacion.scrollTop=conversacion.scrollHeight;}
  function responder(texto){agregar(texto,'usuario');setTimeout(()=>agregar(respuestas[texto]||`He recibido tu consulta sobre “${texto}”. En esta maqueta puedo orientarte mediante los accesos rápidos y la información visible del módulo ${modulo}.`),350);}
  // Se delega desde el documento para que el botón continúe funcionando al
  // trasladarse al encabezado común de cualquier módulo.
  document.addEventListener('click',evento=>{
    const activador=evento.target.closest('#botonAsistenteIA');
    if(!activador)return;
    evento.preventDefault();
    alternar(panel.hidden);
  });
  document.getElementById('cerrarAsistenteIA').addEventListener('click',()=>alternar(false));
  conversacion.querySelectorAll('.acciones-rapidas-ia button').forEach(opcion=>opcion.addEventListener('click',()=>responder(opcion.textContent)));
  formulario.addEventListener('submit',evento=>{evento.preventDefault();const texto=entrada.value.trim();if(!texto)return;entrada.value='';responder(texto);});
  document.addEventListener('keydown',evento=>{if(evento.key==='Escape'&&!panel.hidden)alternar(false);});
})();
