(()=>{
  const clave='masificacion.contratista.liquidacion';
  const base=[
    {codigo:'COMPONENTE 01',nombre:'PSR-GNL / Planta de regasificación',detalle:'Hitos y actas de planta',hito:'Packing list y Bill of Lading',porcentaje:'10',servicio:'Planta satélite de regasificación',unidad:'Planta',cantidad:'1',avance:'0'},
    {codigo:'COMPONENTE 02',nombre:'Redes de distribución',detalle:'Metrados y dossier de obra',hito:'Acta de llegada y obras eléctricas',porcentaje:'25',servicio:'Redes de abastecimiento',unidad:'km',cantidad:'25',avance:'0'},
    {codigo:'COMPONENTE 03',nombre:'Tuberías de conexión',detalle:'Lotes de suministros habilitados',hito:'Pruebas y puesta en operación',porcentaje:'65',servicio:'Tuberías de conexión',unidad:'und',cantidad:'1000',avance:'0'}
  ];
  const leer=()=>{try{return JSON.parse(localStorage.getItem(clave)||'{}')}catch{return {}}};
  const esc=valor=>String(valor??'').replace(/[&<>"']/g,caracter=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[caracter]));
  const campo=(_tipo,_indice,_nombre,valor)=>`<span class="liq-valor" title="Información contractual no editable">${esc(valor)||'—'}</span>`;
  const iconoRequisitos='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h11l3 3v15H5zM16 3v4h4M8 11h8M8 15h5M8 19h5"/><path d="m8 8 1.5 1.5L12 7"/></svg>';
  const iconoEliminar='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>';
  const iconoEnviar='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h14"/><path d="m13 6 6 6-6 6"/></svg>';
  const iconoEnviado='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>';
  const botonesAccion=(id)=>`<span class="liq-accion"><button type="button" class="liq-toggle" data-liq-toggle="${id}" title="Mostrar requisitos" aria-label="Mostrar requisitos" aria-expanded="false">${iconoRequisitos}</button><button type="button" class="liq-enviar" data-liq-enviar title="Enviar a revisión" aria-label="Enviar a revisión">${iconoEnviar}</button></span>`;
  const iconoVista='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.7"/></svg>';
  const botonAdjunto=(indice,adjunto,documentos=[])=>`<button type="button" class="liq-adjuntar" data-liq-adjuntar data-liq-indice="${indice}" data-liq-adjunto="${adjunto}" ${documentos.length?`data-liq-documentos="${esc(JSON.stringify(documentos))}"`:''}>${documentos.length?`${documentos.length} PDF${documentos.length===1?'':'s'} adjunto${documentos.length===1?'':'s'}`:'Adjuntar PDF'}</button><button type="button" class="liq-ver" data-liq-ver title="Ver sustentos" aria-label="Ver sustentos">${iconoVista}</button>`;
  const filaRequisito=(indice,tipo,requisito={},numero=0)=>`<tr data-liq-requisito="${numero}"><td>${campo(tipo,indice,`requisito-${numero}-descripcion`,requisito.descripcion||'Documento de sustento')}</td><td>${campo(tipo,indice,`requisito-${numero}-unidad`,requisito.unidad||'Documento')}</td><td>${campo(tipo,indice,`requisito-${numero}-cantidad`,requisito.cantidad||'1', 'inputmode="numeric"')}</td><td>${campo(tipo,indice,`requisito-${numero}-avance`,requisito.avance||'0', 'inputmode="numeric"')}</td><td><button type="button" class="liq-adjuntar" data-liq-adjuntar data-liq-indice="${indice}" data-liq-adjunto="${tipo}-requisito-${numero}">Adjuntar PDF</button><button type="button" class="liq-ver" data-liq-ver title="Ver sustento" aria-label="Ver sustento">${iconoVista}</button></td></tr>`;
  const requisitos=(indice,tipo,datos)=>`<section class="liq-bloque liq-requisitos" id="requisitos-${tipo}-${indice}" hidden><h4>Requisitos</h4><div class="liq-tabla-wrap"><table><thead><tr><th>Descripción</th><th>Unidad</th><th>Cantidad</th><th>Avance</th><th>Sustento</th></tr></thead><tbody data-liq-requisitos="${tipo}-${indice}">${(datos.requisitos||[{}]).map((requisito,numero)=>filaRequisito(indice,tipo,requisito,numero)).join('')}</tbody></table></div></section>`;
  const estado=(_tipo,_indice,valor)=>`<span class="liq-estado ${String(valor||'Observado').toLowerCase()}">${esc(valor||'Observado')}</span>`;
  const tablaHitos=(indice,datos)=>`<section class="liq-bloque"><h4>Hitos de pago</h4><div class="liq-tabla-wrap"><table><thead><tr><th>Entidad responsable</th><th>Descripción</th><th>% contractual</th><th>Fecha prevista</th><th>Estado</th><th>Sustento</th><th>Acción</th></tr></thead><tbody><tr><td><span class="liq-entidad">FISE</span></td><td>${campo('hito',indice,'descripcion',datos.hito)}</td><td>${campo('hito',indice,'porcentaje',datos.porcentaje,'inputmode="decimal"')}</td><td>${campo('hito',indice,'fecha',datos.fecha||'','type="date"')}</td><td>${estado('hito',indice,datos.estadoHito||'Observado')}</td><td>${botonAdjunto(indice,'hito',datos.adjuntosLista?.hito||[])}</td><td>${botonesAccion(`requisitos-hito-${indice}`)}</td></tr></tbody></table></div>${requisitos(indice,'hito',datos.hitoDatos||{})}</section>`;
  const tablaServicios=(indice,datos)=>`<section class="liq-bloque"><h4>Servicios</h4><div class="liq-tabla-wrap"><table><thead><tr><th>Entidad responsable</th><th>Descripción</th><th>Unidad</th><th>Cantidad</th><th>Avance físico</th><th>Estado</th><th>Sustento</th><th>Acción</th></tr></thead><tbody><tr><td><span class="liq-entidad">FISE</span></td><td>${campo('servicio',indice,'descripcion',datos.servicio)}</td><td>${campo('servicio',indice,'unidad',datos.unidad)}</td><td>${campo('servicio',indice,'cantidad',datos.cantidad,'inputmode="numeric"')}</td><td>${campo('servicio',indice,'avance',datos.avance,'inputmode="decimal"')}</td><td>${estado('servicio',indice,datos.estadoServicio||'Conforme')}</td><td>${botonAdjunto(indice,'servicio',datos.adjuntosLista?.servicio||[])}</td><td>${botonesAccion(`requisitos-servicio-${indice}`)}</td></tr></tbody></table></div>${requisitos(indice,'servicio',datos.servicioDatos||{})}</section>`;
  const plantilla=()=>{const guardado=leer();return `<section class="liquidacion-contratista subtablas-ficha-final"><p class="liq-aviso"><span>Complete los hitos, servicios, requisitos y sustentos de cada componente.</span><button type="button" class="liq-guardar">Guardar cambios</button></p>${base.map((componente,indice)=>{const datos={...componente,...(guardado[indice]||{})};return `<details ${indice===0?'open':''}><summary><span><small>${componente.codigo}</small><strong>${componente.nombre}</strong><em>${componente.detalle}</em></span><b>⌄</b></summary><div class="liq-cuerpo"><i class="subtablas-ficha-final liq-compatibilidad" hidden></i>${tablaHitos(indice,datos)}${tablaServicios(indice,datos)}<p class="liq-nota">Los sustentos adjuntos quedan disponibles para revisión del Interventor.</p></div></details>`;}).join('')}</section>`;};
  const guardar=contenedor=>{const datos=leer();contenedor.querySelectorAll('[data-liq-campo]').forEach(control=>{const indice=control.dataset.liqIndice,tipo=control.dataset.liqTipo,campoNombre=control.dataset.liqCampo;datos[indice]??={};if(tipo==='hito'){datos[indice].hitoDatos??={};if(['descripcion','porcentaje','fecha','estado'].includes(campoNombre))datos[indice][campoNombre==='descripcion'?'hito':campoNombre==='estado'?'estadoHito':campoNombre]=control.value;else{const [,numero,nombre]=campoNombre.match(/^requisito-(\d+)-(.*)$/)||[];if(numero!==undefined){datos[indice].hitoDatos.requisitos??=[];datos[indice].hitoDatos.requisitos[Number(numero)]??={};datos[indice].hitoDatos.requisitos[Number(numero)][nombre]=control.value;}}}else{datos[indice].servicioDatos??={};if(['descripcion','unidad','cantidad','avance','estado'].includes(campoNombre))datos[indice][campoNombre==='descripcion'?'servicio':campoNombre==='estado'?'estadoServicio':campoNombre]=control.value;else{const [,numero,nombre]=campoNombre.match(/^requisito-(\d+)-(.*)$/)||[];if(numero!==undefined){datos[indice].servicioDatos.requisitos??=[];datos[indice].servicioDatos.requisitos[Number(numero)]??={};datos[indice].servicioDatos.requisitos[Number(numero)][nombre]=control.value;}}}});contenedor.querySelectorAll('[data-liq-adjunto][data-liq-documentos]').forEach(boton=>{const indice=boton.dataset.liqIndice,documentos=JSON.parse(boton.dataset.liqDocumentos||'[]');if(!documentos.length)return;datos[indice]??={};datos[indice].adjuntos??={};datos[indice].adjuntosUrl??={};datos[indice].adjuntosLista??={};const claveAdjunto=boton.dataset.liqAdjunto;datos[indice].adjuntos[claveAdjunto]=documentos.map(documento=>documento.nombre).join(', ');datos[indice].adjuntosUrl[claveAdjunto]=documentos[0].url||'';datos[indice].adjuntosLista[claveAdjunto]=documentos;});localStorage.setItem(clave,JSON.stringify(datos));return datos;};
  const agregarRequisito=(boton)=>{const cuerpo=boton.closest('.liq-requisitos'),[tipo,indice]=cuerpo.querySelector('tbody').dataset.liqRequisitos.split('-'),tabla=cuerpo.querySelector('tbody'),numero=tabla.children.length;tabla.insertAdjacentHTML('beforeend',filaRequisito(indice,tipo,{},numero));};
  const leerDocumentos=boton=>{const adjuntar=boton.previousElementSibling;try{return JSON.parse(adjuntar?.dataset.liqDocumentos||'[]')}catch{return []}};
  const vistaPdf=(documento)=>{let dialog=document.getElementById('vistaPdfContratista');if(!dialog){dialog=document.createElement('dialog');dialog.id='vistaPdfContratista';dialog.className='vista-sustento-contratista';document.body.append(dialog);}dialog.innerHTML=`<header><strong>${esc(documento.nombre)}</strong><button type="button" aria-label="Cerrar">×</button></header><div>${documento.url?`<iframe src="${documento.url}" title="${esc(documento.nombre)}"></iframe>`:'<p>El PDF está listo para consulta.</p>'}</div>`;dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.showModal();};
  const verSustento=boton=>{const documentos=leerDocumentos(boton);let dialog=document.getElementById('listaSustentosContratista');if(!dialog){dialog=document.createElement('dialog');dialog.id='listaSustentosContratista';dialog.className='vista-sustento-contratista';document.body.append(dialog);}dialog.innerHTML=`<header><strong>Documentos adjuntos</strong><button type="button" aria-label="Cerrar">×</button></header><div>${documentos.length?`<table class="liq-documentos"><thead><tr><th>Documento PDF</th><th>Acción</th></tr></thead><tbody>${documentos.map((documento,indice)=>`<tr><td>${esc(documento.nombre)}</td><td><button type="button" class="liq-ver" data-liq-pdf="${indice}" title="Ver PDF" aria-label="Ver PDF">${iconoVista}</button></td></tr>`).join('')}</tbody></table>`:'<p>Aún no se adjuntaron PDFs para este registro.</p>'}</div>`;dialog.querySelector('header button').addEventListener('click',()=>dialog.close());dialog.querySelectorAll('[data-liq-pdf]').forEach(botonPdf=>botonPdf.addEventListener('click',()=>{const documento=documentos[Number(botonPdf.dataset.liqPdf)];if(documento)vistaPdf(documento);}));dialog.showModal();};
  const adjuntarPdf=(boton,contenedor)=>{let dialog=document.getElementById('adjuntarPdfContratista');if(!dialog){dialog=document.createElement('dialog');dialog.id='adjuntarPdfContratista';dialog.className='vista-sustento-contratista liq-modal-adjuntar';document.body.append(dialog);}const cargar=archivos=>{const pdfs=[...archivos].filter(archivo=>archivo.type==='application/pdf'||archivo.name.toLowerCase().endsWith('.pdf'));if(!pdfs.length)return;const pendientes=pdfs.map(archivo=>new Promise(resolve=>{const lector=new FileReader();lector.onload=()=>resolve({nombre:archivo.name,url:String(lector.result||'')});lector.readAsDataURL(archivo);}));Promise.all(pendientes).then(documentos=>{boton.dataset.liqDocumentos=JSON.stringify(documentos);boton.textContent=`${documentos.length} PDF${documentos.length===1?'':'s'} adjunto${documentos.length===1?'':'s'}`;guardar(contenedor);dialog.close();});};dialog.innerHTML=`<header><div><small>GESTIÓN CONTRACTUAL</small><strong>Adjuntar PDFs · Contratista</strong></div><button type="button" aria-label="Cerrar">×</button></header><div><label class="liq-zona-carga" data-liq-zona><span>⇧</span><b>Arrastre uno o varios PDF aquí</b><em>o selecciónelos desde su equipo</em><button type="button" class="liq-buscar">Buscar archivos</button><small>Formato permitido: PDF.</small><input type="file" accept="application/pdf,.pdf" multiple hidden></label><p>Los documentos quedarán disponibles para revisión del Interventor.</p></div><footer><button type="button" class="liq-cancelar">Cancelar</button></footer>`;const input=dialog.querySelector('input'),zona=dialog.querySelector('[data-liq-zona]');dialog.querySelector('header button').addEventListener('click',()=>dialog.close());dialog.querySelector('.liq-cancelar').addEventListener('click',()=>dialog.close());dialog.querySelector('.liq-buscar').addEventListener('click',evento=>{evento.preventDefault();input.click();});input.addEventListener('change',()=>cargar(input.files));['dragenter','dragover'].forEach(evento=>zona.addEventListener(evento,eventoDom=>{eventoDom.preventDefault();zona.classList.add('arrastrando');}));['dragleave','drop'].forEach(evento=>zona.addEventListener(evento,eventoDom=>{eventoDom.preventDefault();zona.classList.remove('arrastrando');}));zona.addEventListener('drop',evento=>cargar(evento.dataTransfer.files));dialog.showModal();};
  const instalar=()=>{const ficha=document.querySelector('.vista-ficha-cusco');if(!ficha)return;const panel=ficha.querySelector('.cierre-ficha-masificacion [data-cierre-panel="documentos"]');if(!panel)return;if(!panel.querySelector('.liquidacion-contratista')){panel.innerHTML=plantilla();}const contenedor=panel.querySelector('.liquidacion-contratista');if(contenedor.dataset.inicializado)return;contenedor.dataset.inicializado='si';contenedor.addEventListener('input',()=>guardar(contenedor));contenedor.addEventListener('change',()=>guardar(contenedor));contenedor.addEventListener('click',evento=>{const boton=evento.target.closest('button');if(!boton)return;if(boton.classList.contains('liq-guardar')){guardar(contenedor);boton.textContent='Guardado ✓';setTimeout(()=>boton.textContent='Guardar cambios',1600);}if(boton.dataset.liqToggle){const requisitos=document.getElementById(boton.dataset.liqToggle);if(requisitos){requisitos.hidden=!requisitos.hidden;boton.classList.toggle('activo',!requisitos.hidden);boton.setAttribute('aria-expanded',String(!requisitos.hidden));boton.setAttribute('aria-label',requisitos.hidden?'Mostrar requisitos':'Ocultar requisitos');}}if(boton.hasAttribute('data-liq-enviar')){guardar(contenedor);boton.innerHTML=iconoEnviado;boton.title='Enviado a revisión';boton.setAttribute('aria-label','Enviado a revisión');boton.disabled=true;}if(boton.hasAttribute('data-liq-adjuntar'))adjuntarPdf(boton,contenedor);if(boton.hasAttribute('data-liq-ver'))verSustento(boton);});};
  const observar=()=>{instalar();new MutationObserver(instalar).observe(document.body,{childList:true,subtree:true});};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observar);else observar();
})();
